version: '3.8'

services:
  # Express.js
  app:
    build: .
    ports:
      - '8080:3000'
    env_file:
      - .env
    depends_on:
      - db

  # MongoDB
  db:
    image: docker.io/library/mongo:4.4
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
