version: '3.8'

services:
  # Express.js
  app:
    build: .
    ports:
      - '8080:3000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # MongoDB
  db:
    image: docker.io/library/mongo:4.4
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: "mongo --eval 'db.stats()' || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongo-data:
